stream.rules = [
  {
    matches = [
      { node.name = "discord_sink" }
      { node.name = "catchall_sink" }
    ]
    actions = {
      update-props = {
        state.restore-props = false
      }
    }
  }
]
